CREATE TABLE IF NOT EXISTS `#__cggallery_page` (
`id` integer NOT NULL AUTO_INCREMENT,
`title` text NOT NULL,
`state` integer NOT NULL default 0,
`page_params` text NOT NULL,
`intro` text,
`bottom` text,
`ug_compression` int DEFAULT '0',
`ug_type` varchar(50) DEFAULT '',
`ug_tiles_type` varchar(50) DEFAULT '',
`ug_tile_width` int DEFAULT '0',
`ug_min_columns` int DEFAULT '0',
`ug_tile_height` int DEFAULT '0',
`ug_grid_num_rows` int DEFAULT '0',
`ug_space_between_rows` int DEFAULT '0',
`ug_space_between_cols` int DEFAULT '0',
`ug_carousel_autoplay_timeout` int DEFAULT '0',
`ug_carousel_scroll_duration` int DEFAULT '0',
`ug_text` text,
`ug_text_lgth` int DEFAULT '0',
`ug_link` varchar(10) DEFAULT 'false',
`ug_lightbox` varchar(10) DEFAULT 'false',
`ug_dir_or_image` varchar(10) DEFAULT 'dir',
`ug_skin` text,
`ug_autothumb` varchar(10),
`ug_big_dir` text,
`ug_full_dir` text,
`ug_file_nb` int DEFAULT '0',
`ug_grid_thumbs_pos` varchar(10) DEFAULT 'left',
`ug_grid_show_icons` varchar(10) DEFAULT 'false',
`ug_articles` text,
`imgtypes` varchar(50) DEFAULT NULL,
`slides` text NOT NULL ,
`created` datetime NOT NULL DEFAULT '1980-01-01 00:00:00',
`created_by` int(10) unsigned NOT NULL DEFAULT '0',
`modified` datetime NOT NULL DEFAULT '1980-01-01 00:00:00',
`modified_by` int(10) unsigned NOT NULL DEFAULT '0',
`checked_out` int(10) unsigned NOT NULL DEFAULT '0',
`checked_out_time` datetime NOT NULL DEFAULT '1980-01-01 00:00:00',
`publish_up` datetime NOT NULL DEFAULT '1980-01-01 00:00:00',
`publish_down` datetime NOT NULL DEFAULT '1980-01-01 00:00:00',
`language` char(7) NOT NULL DEFAULT '',
PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='CG Gallery definition des sections';
